//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiNo.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class D受診者情報
    {
        public string 患者番号 { get; set; }
        public string 漢字氏名 { get; set; }
        public string かな氏名 { get; set; }
        public string イニシャル { get; set; }
        public Nullable<System.DateTime> 生年月日 { get; set; }
        public Nullable<byte> 性別 { get; set; }
        public Nullable<byte> 血液型abo { get; set; }
        public Nullable<byte> 血液型rh { get; set; }
        public string 郵便番号 { get; set; }
        public string 住所1 { get; set; }
        public string 住所2 { get; set; }
        public string 連絡先電話番号 { get; set; }
        public string 自宅電話番号 { get; set; }
        public string 携帯電話番号 { get; set; }
        public string ｆａｘ番号 { get; set; }
        public string 電子メールアドレス { get; set; }
        public string メモ1 { get; set; }
        public string メモ2 { get; set; }
        public string マイナンバー { get; set; }
        public Nullable<short> 担当医no { get; set; }
        public Nullable<System.DateTime> 最終更新日付 { get; set; }
        public Nullable<System.DateTime> 出産予定日 { get; set; }
    }
}
