//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiNo.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class D受診データ追加食
    {
        public string 患者番号 { get; set; }
        public System.DateTime 配膳日 { get; set; }
        public Nullable<byte> 大人食1 { get; set; }
        public Nullable<byte> 子供食1 { get; set; }
        public Nullable<byte> 大人食2 { get; set; }
        public Nullable<byte> 子供食2 { get; set; }
        public Nullable<byte> 大人食3 { get; set; }
        public Nullable<byte> 子供食3 { get; set; }
    }
}
