//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiNo.API
{
    using System;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class D受診データ
    {
        public int orderno { get; set; }
        
        [JsonProperty("LoginDate")]
        public Nullable<System.DateTime> 書込日時 { get; set; }
        public string 患者番号 { get; set; }
        public string 漢字氏名 { get; set; }
        public string かな氏名 { get; set; }
        public string イニシャル { get; set; }
        public Nullable<System.DateTime> 生年月日 { get; set; }
        public Nullable<byte> 性別 { get; set; }
        public Nullable<byte> 血液型abo { get; set; }
        public Nullable<byte> 血液型rh { get; set; }
        public string 郵便番号 { get; set; }
        public string 住所1 { get; set; }
        public string 住所2 { get; set; }
        public string 連絡先電話番号 { get; set; }
        public string 自宅電話番号 { get; set; }
        public string 携帯電話番号 { get; set; }
        public string ｆａｘ番号 { get; set; }
        public string 電子メールアドレス { get; set; }
        public string メモ1 { get; set; }
        public string メモ2 { get; set; }
        public string マイナンバー { get; set; }
        public Nullable<short> 担当医 { get; set; }
        public Nullable<byte> 性別子1 { get; set; }
        public Nullable<byte> 性別子2 { get; set; }
        public string 病室状態1 { get; set; }
        public string 病室状態2 { get; set; }
        public Nullable<short> 病室no { get; set; }
        public Nullable<System.DateTime> 入院日 { get; set; }
        public Nullable<System.DateTime> 退院日 { get; set; }
        public Nullable<System.DateTime> 分娩日 { get; set; }
        public string 特記事項1 { get; set; }
        public string 特記事項2 { get; set; }
        public string 病室希望1 { get; set; }
        public string 病室希望2 { get; set; }
        public string アレルギ { get; set; }
        public Nullable<byte> flg1 { get; set; }
        public Nullable<byte> flg2 { get; set; }
        public Nullable<byte> flg3 { get; set; }
        public Nullable<byte> flg4 { get; set; }
        public Nullable<byte> flg5 { get; set; }
        public Nullable<byte> flg6 { get; set; }
        public Nullable<byte> flg7 { get; set; }
        public Nullable<byte> flg8 { get; set; }
        public Nullable<byte> flg9 { get; set; }
        public Nullable<byte> flg10 { get; set; }
        public Nullable<byte> option1 { get; set; }
        public Nullable<byte> option2 { get; set; }
        public Nullable<byte> option3 { get; set; }
        public Nullable<byte> option4 { get; set; }
        public Nullable<byte> option5 { get; set; }
        public Nullable<byte> option6 { get; set; }
        public Nullable<byte> option7 { get; set; }
        public Nullable<byte> option8 { get; set; }
        public Nullable<byte> option9 { get; set; }
        public Nullable<byte> option10 { get; set; }
        public string 備考1 { get; set; }
        public string 備考2 { get; set; }
        public string 備考3 { get; set; }
        public string 備考4 { get; set; }
        public string 備考5 { get; set; }
        public string 備考6 { get; set; }
        public string 備考7 { get; set; }
        public string 備考8 { get; set; }
        public string 備考9 { get; set; }
        public string 備考10 { get; set; }
        public string rsv_cha1 { get; set; }
        public string rsv_cha2 { get; set; }
        public string rsv_cha3 { get; set; }
        public string rsv_cha4 { get; set; }
        public string rsv_cha5 { get; set; }
        public string rsv_cha6 { get; set; }
        public string rsv_cha7 { get; set; }
        public string rsv_cha8 { get; set; }
        public string rsv_cha9 { get; set; }
        public string rsv_cha10 { get; set; }
        public Nullable<long> rsv_num1 { get; set; }
        public Nullable<long> rsv_num2 { get; set; }
        public Nullable<long> rsv_num3 { get; set; }
        public Nullable<long> rsv_num4 { get; set; }
        public Nullable<long> rsv_num5 { get; set; }
        public Nullable<long> rsv_num6 { get; set; }
        public Nullable<long> rsv_num7 { get; set; }
        public Nullable<long> rsv_num8 { get; set; }
        public Nullable<long> rsv_num9 { get; set; }
        public Nullable<long> rsv_num10 { get; set; }
        public Nullable<short> 大人食1 { get; set; }
        public Nullable<short> 子供食1 { get; set; }
        public Nullable<short> 大人食2 { get; set; }
        public Nullable<short> 子供食2 { get; set; }
        public Nullable<short> 大人食3 { get; set; }
        public Nullable<short> 子供食3 { get; set; }
        public Nullable<System.DateTime> 出産予定日履歴用 { get; set; }
        public Nullable<System.DateTime> 重要情報更新日時 { get; set; }
        public Nullable<byte> トリガー実行フラグ { get; set; }
    }
}
