//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiNo.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class M性別
    {
        public byte 性別 { get; set; }
        public string 入力コード1 { get; set; }
        public string 入力コード2 { get; set; }
        public string 入力コード3 { get; set; }
        public string 略称 { get; set; }
        public string 名称 { get; set; }
        public string ホストコード1 { get; set; }
        public string ホストコード2 { get; set; }
        public string ホストコード3 { get; set; }
        public Nullable<double> 予備数字1 { get; set; }
        public Nullable<double> 予備数字2 { get; set; }
        public string 予備文字1 { get; set; }
        public string 予備文字2 { get; set; }
    }
}
