//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiNo.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class M担当医
    {
        public short 担当医no { get; set; }
        public string 漢字略称 { get; set; }
        public string カナ名称 { get; set; }
        public string 漢字正式名称 { get; set; }
        public string 色コード { get; set; }
        public string ホストコード1 { get; set; }
        public string ホストコード2 { get; set; }
        public string ホストコード3 { get; set; }
    }
}
