//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiNo.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class M病室
    {
        public short 病室no { get; set; }
        public string 病室名 { get; set; }
        public Nullable<bool> 使用flg { get; set; }
        public Nullable<bool> 詰所印刷flg { get; set; }
        public Nullable<bool> ra印刷flg { get; set; }
    }
}
