//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiNo.API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiNoEntities : DbContext
    {
        public MiNoEntities()
            : base("name=MiNoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<D受診データ> D受診データ { get; set; }
        public virtual DbSet<D受診データ追加食> D受診データ追加食 { get; set; }
        public virtual DbSet<D受診者情報> D受診者情報 { get; set; }
        public virtual DbSet<M性別> M性別 { get; set; }
        public virtual DbSet<M担当医> M担当医 { get; set; }
        public virtual DbSet<M病室> M病室 { get; set; }
    }
}
